# Craft configuration
---

repositories:
  local:
    target: http://localhost/craft/local
    handler: wget -c
    #env:
      #http_proxy: "http://ucs-gw.ucs.br:3128"

architectures:
  default: amd64
  enabled:
    - amd64
    - sparc

groups:
  - base
  - xorg

root: /home/martin/University/craft/craft-package-manager/root
db: /home/martin/University/craft/craft-package-manager/db
